### ISSUE TITLE
API errors have no information

### ISSUE THREAD

**Issue by bruno-campos** [Bandwidth/ruby-bandwidth-iris#62]
When errors happen in HTTP requests, the gem throws an exception:
```
BandwidthIris::Errors::GenericError (Http code 400)
```

It doesn't return the API response nor the real API HTTP error status. This limits debugging issues that happened when using the gem

**Comment by ajrice6713** [comment]
Hey @bruno-campos 

thanks for raising this issue - our team works in 2 week sprints and we have a new one starting next week. We will add this to our backlog and hopefully investigate and update you next week.

**Comment by ckoegel** [comment]
Hi @bruno-campos. I've been looking into this issue and have been able to recreate it to some extent. The error handling currently in place does a bad job of logging the HTTP error, but that status code shown after `Http code` does seem to be correct and can also be accessed with `http_status` if the error is caught. i.e
```ruby
begin
  # http call
rescue BandwidthIris::Errors::GenericError => e
  puts e.http_status
end
```

Currently, we are using the built in response from faraday to loosely build the `GenericError` model, but we are not giving the error model anything other than the status code. In #63, I've updated this model to contain more info from the faraday response. This information can be viewed in the updated error message if the error is not caught, or accessed within the caught error similar to the example above. Do note that in order to keep this from being a breaking change, I did not populate the `code` attribute that should represent the Iris error code. This can still be accessed/seen within the response body if one exists.

**Comment by ckoegel** [comment]
Update:
#63 Has been modified to not change the error message to remain non-breaking, but the new response info is still accessible. This change will go out in our release set for tomorrow (4/12/22). There will then be another breaking change made that will update the error message and add support for populating the iris error code. This will be added to a new major version release on 4/26/22.

**Comment by ckoegel** [comment]
#64 Contains the new breaking error model changes.
